// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleInitParameters struct {

	// key of the custom rule should only contain : a-z, 0-9, \_
	CustomKey *string `json:"customKey,omitempty" tf:"custom_key,omitempty"`

	// Rule description
	MarkdownDescription *string `json:"markdownDescription,omitempty" tf:"markdown_description,omitempty"`

	// Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Parameters as semi-colon list of =, for example 'params=key1=v1;key2=v2' (Only for custom rule)
	// - parameter order: expression=value;filePattern=value;message=value
	Params *string `json:"params,omitempty" tf:"params,omitempty"`

	// If set to true and if the rule has been deactivated (status 'REMOVED'), a status 409 will be returned
	// - Possible values - true, false, yes, no
	PreventReactivation *string `json:"preventReactivation,omitempty" tf:"prevent_reactivation,omitempty"`

	// Rule severity
	// - Possible values - INFO, MINOR, MAJOR, CRITICAL, BLOCKER
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Rule status
	// - Possible values - BETA, DEPRECATED, READY, REMOVED
	// - Default value - READY
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key of the template rule in order to create a custom rule (mandatory for custom rule)
	// - [Example values](https://docs.sonarqube.org/latest/user-guide/rules/#header-4)
	TemplateKey *string `json:"templateKey,omitempty" tf:"template_key,omitempty"`

	// Rule type
	// - Possible values - CODE_SMELL, BUG, VULNERABILITY, SECURITY_HOTSPOT
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RuleObservation struct {

	// key of the custom rule should only contain : a-z, 0-9, \_
	CustomKey *string `json:"customKey,omitempty" tf:"custom_key,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Rule description
	MarkdownDescription *string `json:"markdownDescription,omitempty" tf:"markdown_description,omitempty"`

	// Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Parameters as semi-colon list of =, for example 'params=key1=v1;key2=v2' (Only for custom rule)
	// - parameter order: expression=value;filePattern=value;message=value
	Params *string `json:"params,omitempty" tf:"params,omitempty"`

	// If set to true and if the rule has been deactivated (status 'REMOVED'), a status 409 will be returned
	// - Possible values - true, false, yes, no
	PreventReactivation *string `json:"preventReactivation,omitempty" tf:"prevent_reactivation,omitempty"`

	// Rule severity
	// - Possible values - INFO, MINOR, MAJOR, CRITICAL, BLOCKER
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Rule status
	// - Possible values - BETA, DEPRECATED, READY, REMOVED
	// - Default value - READY
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key of the template rule in order to create a custom rule (mandatory for custom rule)
	// - [Example values](https://docs.sonarqube.org/latest/user-guide/rules/#header-4)
	TemplateKey *string `json:"templateKey,omitempty" tf:"template_key,omitempty"`

	// Rule type
	// - Possible values - CODE_SMELL, BUG, VULNERABILITY, SECURITY_HOTSPOT
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RuleParameters struct {

	// key of the custom rule should only contain : a-z, 0-9, \_
	// +kubebuilder:validation:Optional
	CustomKey *string `json:"customKey,omitempty" tf:"custom_key,omitempty"`

	// Rule description
	// +kubebuilder:validation:Optional
	MarkdownDescription *string `json:"markdownDescription,omitempty" tf:"markdown_description,omitempty"`

	// Rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Parameters as semi-colon list of =, for example 'params=key1=v1;key2=v2' (Only for custom rule)
	// - parameter order: expression=value;filePattern=value;message=value
	// +kubebuilder:validation:Optional
	Params *string `json:"params,omitempty" tf:"params,omitempty"`

	// If set to true and if the rule has been deactivated (status 'REMOVED'), a status 409 will be returned
	// - Possible values - true, false, yes, no
	// +kubebuilder:validation:Optional
	PreventReactivation *string `json:"preventReactivation,omitempty" tf:"prevent_reactivation,omitempty"`

	// Rule severity
	// - Possible values - INFO, MINOR, MAJOR, CRITICAL, BLOCKER
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Rule status
	// - Possible values - BETA, DEPRECATED, READY, REMOVED
	// - Default value - READY
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key of the template rule in order to create a custom rule (mandatory for custom rule)
	// - [Example values](https://docs.sonarqube.org/latest/user-guide/rules/#header-4)
	// +kubebuilder:validation:Optional
	TemplateKey *string `json:"templateKey,omitempty" tf:"template_key,omitempty"`

	// Rule type
	// - Possible values - CODE_SMELL, BUG, VULNERABILITY, SECURITY_HOTSPOT
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// RuleSpec defines the desired state of Rule
type RuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleInitParameters `json:"initProvider,omitempty"`
}

// RuleStatus defines the observed state of Rule.
type RuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rule is the Schema for the Rules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonarqube}
type Rule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.customKey) || (has(self.initProvider) && has(self.initProvider.customKey))",message="spec.forProvider.customKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.markdownDescription) || (has(self.initProvider) && has(self.initProvider.markdownDescription))",message="spec.forProvider.markdownDescription is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateKey) || (has(self.initProvider) && has(self.initProvider.templateKey))",message="spec.forProvider.templateKey is a required parameter"
	Spec   RuleSpec   `json:"spec"`
	Status RuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleList contains a list of Rules
type RuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rule `json:"items"`
}

// Repository type metadata.
var (
	Rule_Kind             = "Rule"
	Rule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rule_Kind}.String()
	Rule_KindAPIVersion   = Rule_Kind + "." + CRDGroupVersion.String()
	Rule_GroupVersionKind = CRDGroupVersion.WithKind(Rule_Kind)
)

func init() {
	SchemeBuilder.Register(&Rule{}, &RuleList{})
}
