// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GitLabInitParameters struct {

	// (String) Unique key of the GitLab instance setting. Maximum length: 200
	// Unique key of the GitLab instance setting. Maximum length: 200
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String, Sensitive) GitLab App personal access token with the read_api scope. See this doc for more information. Maximum length: 2000
	// GitLab App personal access token with the `read_api` scope. See [this doc](https://docs.sonarqube.org/latest/devops-platform-integration/gitlab-integration/#importing-your-gitlab-projects-into-sonarqube) for more information. Maximum length: 2000
	PersonalAccessTokenSecretRef v1.SecretKeySelector `json:"personalAccessTokenSecretRef" tf:"-"`

	// (String) GitLab API URL. Maximum length: 2000
	// GitLab API URL. Maximum length: 2000
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitLabObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique key of the GitLab instance setting. Maximum length: 200
	// Unique key of the GitLab instance setting. Maximum length: 200
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) GitLab API URL. Maximum length: 2000
	// GitLab API URL. Maximum length: 2000
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitLabParameters struct {

	// (String) Unique key of the GitLab instance setting. Maximum length: 200
	// Unique key of the GitLab instance setting. Maximum length: 200
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String, Sensitive) GitLab App personal access token with the read_api scope. See this doc for more information. Maximum length: 2000
	// GitLab App personal access token with the `read_api` scope. See [this doc](https://docs.sonarqube.org/latest/devops-platform-integration/gitlab-integration/#importing-your-gitlab-projects-into-sonarqube) for more information. Maximum length: 2000
	// +kubebuilder:validation:Optional
	PersonalAccessTokenSecretRef v1.SecretKeySelector `json:"personalAccessTokenSecretRef" tf:"-"`

	// (String) GitLab API URL. Maximum length: 2000
	// GitLab API URL. Maximum length: 2000
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// GitLabSpec defines the desired state of GitLab
type GitLabSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GitLabParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GitLabInitParameters `json:"initProvider,omitempty"`
}

// GitLabStatus defines the observed state of GitLab.
type GitLabStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GitLabObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GitLab is the Schema for the GitLabs API. Provides a Sonarqube GitLab Alm/Devops Platform Integration resource. This can be used to create and manage a Alm/Devops Platform Integration for GitLab.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonarqube}
type GitLab struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.personalAccessTokenSecretRef)",message="spec.forProvider.personalAccessTokenSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   GitLabSpec   `json:"spec"`
	Status GitLabStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GitLabList contains a list of GitLabs
type GitLabList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GitLab `json:"items"`
}

// Repository type metadata.
var (
	GitLab_Kind             = "GitLab"
	GitLab_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GitLab_Kind}.String()
	GitLab_KindAPIVersion   = GitLab_Kind + "." + CRDGroupVersion.String()
	GitLab_GroupVersionKind = CRDGroupVersion.WithKind(GitLab_Kind)
)

func init() {
	SchemeBuilder.Register(&GitLab{}, &GitLabList{})
}
