apiVersion: project.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: example-project 
    project: example-project
    visibility: public
